usage: yq . products.yaml > products.json
pipe0: detecting images g "\!\[.+\([^)]+)" details.md -o ais.md  gps.md 
 
products:
- u: diving.html?o=menger&e=cubmau
  i: anim/maunakea.gif
  n: Geometry & Galaxy
  d: Night sky at Maunakea
  k: dive3D
  p: dive,sci
  a: CC BY-SA ZryDys

- u: keyr.html?q=broach&c=0x1111aa
  i: thumb/cune3b.jpg
  n: Broach
  d: 
  k: solid,deco
  p: solid
  a: printables.com/@John_56680  
- u: glsl-fractal.html
  i: anim/glslfract.gif
  n: Fractal shader
  d: 
  k: fractal
  p: fractal
  a: CC BY-SA ZryDys  

- n: Fractal tree
  p: fractal
  i: zrydys.png   
  d: fractal javascript
  k: fractal
- n: Geo maps
  p: maps
  i: tiles/4-8-5.png
  d: CET Berlin area 🇨🇭
  k: travel,gis 
  d: GDAL GeoServers 🌐 Tiles
  u: gis.html
- u: details.html
  n: Agile CI/CD  
  p: info
  k: pm,develop
  i: cicd.jpg
  d: CI/CD Agile
  a: Zrydys

- u: planet.html?q=cach/cor.jpg
  n: 3D Corridor
  k: 3D
  i: cach/cor.jpg
- u: planet.html?q=cach/col.jpg 
  n: Cyber Corridor
  k: cyber,3D
  i: cach/col.jpg
- u: planet.html?q=thumb/humerus.jpg  
  i: thumb/humerus.jpg   
  n: Bones 3D Replica
  d: Humerous 3D 
  k: medic,sci,solid
  p: info
 
  
  
- u: ais.html
  i: https://www.rtl-sdr.com/wp-content/uploads/2020/05/sarcnet_ais.jpg
  n: Safe Marine AIS  
  d: Cyber Raspberry Pi and RTL-SDR Based NOAA Weather Satellite & AIS receiver projects
  k: cyber,telco,nautic
  p: info
  a: authors from NOAA, rtl-sdr.com, zryDys 
 
- u: https://img.tapimg.net/market/images/4d4d88f02aba3559a8ecd7e4498def05.jpg
  g: ?q=https://img.tapimg.net/market/images/4d4d88f02aba3559a8ecd7e4498def05.jpg
  i: thumb/camp.jpg
  n: Camper
  d: Camper Van, Make it Home
  k: game,travel
  p: mvp
  a: Reviews taptap.io/app/33677784  + header by  steamcommunity.com/app/2843190 
- u: planet.html?q=cach/CA.jpg
  i: cach/CA.jpg
  n: MarianCA
  d: Portfolio 
  k: art,deco
  p: mvp
  a: by MarianCustomArt.com 
- u: move.html?q=cach/MD.jpg
  i: thumb/merge.jpg
  n: Merge game moving
  d: Merge with darkness - 3d effect
  k: game
  p: mvp
  a: E.
  
- u: vis-bi-plotly.html
  i: https://github.com/dipterix/threeBrain/blob/master/adhoc/demo.gif?raw=true
  n: R&D+i DatSci ML
  d: cutting-edge technologies
  k: ml,medic,sci
  p: info
  a: zryDys  
- u: planet.html?q=cach/MD.jpg
  n: Merge game 
  k: game
  i: cach/MD.jpg
  d: Merge with darkness 
  a: E. (QR in pic)
- u: planet.html?q=thumb/elvis-always.jpg
  i: anim/elvis.gif
  n: Elvis Piano
  d: Elvis' Always for Piano  
  k: music
  p: mvp
  a: at MuseScore.com 
- u: mvpc.html
  i: thumb/mvpc.jpg
  n: MovePic shader
  d: 
  k: 3D
  p: mvp
  a: ZryDys
- u: escher3D.html
  i: thumb/esch3.jpg
  n: 3D Escher
  d: Tiling
  k: escher,tiles
  p: escher
  a: MCEscher original 1953 + colors added by Zrydys
- u: planet.html?q=cach/M.jpg
  i: cach/M.jpg
  n: Museums Workshop
  d: Bringing cultural near the digital natives
  k: art,culture
  p: mvp
  a: 
- u: planet.html?q=cach/NS.jpg
  i: cach/NS.jpg
  n: Next Stop
  d: game The Next Stop 
  k: game
  p: mvp
  a: by X.com/paranoiddlusion?s=21&t=Y7Vkz-5FGGbo814UUxh4mw 🐦
  
- u: circular.html
  i: https://upload.wikimedia.org/wikipedia/commons/archive/6/67/20210807143407%21Linia_kontra%C5%AD_Cirkulero.svg
  n: Ciscular economy
  d: circular 🌱 economy Tech, NASA TRL aligned 
  k: csr,pm
  p: info
  a: ZryDys csr
  
- u: planet.html?q=cach/SG.jpg
  i: cach/SG.jpg
  n: Sigillum
  d: 
  k: game
  p: mvp
  a: by X.com/closedroomstudio 🐦
- u: diving.html
  i: anim/diving.gif
  n: diving
  d: 
  k: dive3D
  p: dive
  a: CC BY-SA ZryDys
- u: orbitforest.html
  i: anim/forest.gif
  n: forest
  d: 
  k: dive3D
  p: dive
  a: CC BY-SA ZryDys
- u: diving.html?o=tetra&e=cubcon
  i: anim/concert.gif
  n: Pyramids & Concert
  d: 
  k: dive3D
  p: dive
  a: CC BY-SA ZryDys

- u: keyr.html?q=wingfoil&c=0xadadad
  i: thumb/wingfoil3.jpg
  n: Nautic Solid
  d: wingfoil for sailing
  k: nautic,solid
  p: solid
  a: 
- u: keyr.html?q=tetra&c=0xa1a12a
  i: thumb/tetra3.jpg
  n: Pyramid
  d: decorative
  k: solid
  p: solid
- u: keyr.html?q=noc&c=0x1111aa
  i: thumb/noc3.jpg
  n: NOceaNoUs
  d: NOceaNoUs Keyring
  k: solid,nautic
  p: solid
  a: by NOceaNoUs.com
- u: planet.html?q=cach/SR.jpg 
  i: cach/SR.jpg
  n: NOceaNoUs' SeaRangers
  d: NOceaNoUs' SeaRangers game
  k: game,nautic
  p: mvpc
  a: by NOceaNoUs.com
 
- u: keyr.html?q=kite&c=0x41a19a
  i: thumb/kite3.jpg
  n: Kite
  d: for kite surfing
  k: solid,nautic
  p: solid
  a: printables.com/@samster395
- u: keyr.html?q=tactile&c=0x41a19a
  i: thumb/tactile3.jpg
  n: Braille
  d: Facilitating diversity & inclusion 
  k: solid
  p: solid,csr
  a: ZryDys csr
- u: planet.html?q=cach/F.jpg 
  i: cach/F.jpg
  n: Las Futbolistas
  k: game,csr
 
- u: keyr.html?q=inkkey&c=0xff385c
  i: thumb/ink3.jpg
  n: InkUp key
  d: 
  k: solid
  p: solid
  a: InkUp
- u: tiles.html
  i: thumb/alhambra.jpg
  n: Alhambra Tile 
  d: Tiles Alhambra style - use mouse to 3D navigate
  k: maths,tiles
  p: tile
  a: CC BY-SA ZryDys 
- u: tofractal.html
  i: wall/tofractal.jpg
  n: Moving Fractal 
  d: 
  k: fractal
  p: mvp
  a: CC BY-SA ZryDys 
- u: tile.html
  i: thumb/tiles.jpg
  n: tiles 3D
  d: Group Recurrent 3D Tiling
  k: maths,tiles
  p: tile
  a: CC BY-SA ZryDys 
- u: planet.html?q=https://d2v9mhsiek5lbq.cloudfront.net/eyJidWNrZXQiOiJsb21hLW1lZGlhLWl0Iiwia2V5IjoiZG1heHNwYWluLWVzLWltYWdlLWM2NmFiZjAzLWU3ZWItNDcyZi1hOWQ2LTkxZTQ1NGFkZGNjNS5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsiZml0IjoiY292ZXIiLCJoZWlnaHQiOjI0MH0sIndlYnAiOnsicXVhbGl0eSI6ODB9fX0=
  i: https://d2v9mhsiek5lbq.cloudfront.net/eyJidWNrZXQiOiJsb21hLW1lZGlhLWl0Iiwia2V5IjoiZG1heHNwYWluLWVzLWltYWdlLWM2NmFiZjAzLWU3ZWItNDcyZi1hOWQ2LTkxZTQ1NGFkZGNjNS5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsiZml0IjoiY292ZXIiLCJoZWlnaHQiOjI0MH0sIndlYnAiOnsicXVhbGl0eSI6ODB9fX0=
  a: dmax   
  n: machu-pichu peru
  k: travel,art
- u: details.html
  i: thumb/dsci-byUrl.jpg
  n: Us & Symmetry
  d: 
  k: cyber
  p: info
  a: CC BY-SA ZryDys 
- u: visual-plotly.html
  i: wall/z-datsci.jpg
  n: R&D+i DatSci
  d: 
  k: sci,cyber
  p: info
  a: zryDys 
- i: cach/promalaga.jpg
  u: esch4.html?q=cach/promalaga.jpg
  p: box
  d: Impulso funding
  n: co-funded by the Impulso Program
  a: by promalaga.es 
  k: funds,acks

- i: https://ec.europa.eu/regional_policy/images/information-sources/logo-download-center/stickers.png
  r: https://ec.europa.eu/regional_policy/information-sources/logo-download-center_en?cjreferenc
  u: move.html?q=forest.jpg 
  p: box
  d: co-funded by the European Union 
  n: EU funding
  a: by europe.eu FSE
  k: funds,acks
- i: cach/ar.jpg
  u: planet.html?q=cach/ar.jpg
  n: Arrival 2016 
  a: review at reelgood.com/search?q=arrival   
  k: art,music
- i: fractalgold.png
  k: acks,sci
  n: Arc thanks
  d: Acknoledge NASA Arc Resources
  a: by nasa.gov/ 
